apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: telco-llm-platform
  namespace: telco-llm
  labels:
    app: telco-llm
  annotations:
    haproxy.router.openshift.io/timeout: 60s
spec:
  to:
    kind: Service
    name: telco-llm-platform
    weight: 100
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None

  